name: Update README with Random Quote

on:
  schedule:
    - cron: "0 * * * *"  # Jalan setiap jam
  workflow_dispatch:       # Bisa dijalankan manual dari GitHub Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Full Access)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Ambil semua history biar bisa rebase

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Run Script
        run: node quote_generator.mjs

      - name: Debug README Content
        run: cat README.md

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Pull Latest Changes (Safe Rebase)
        run: git pull origin main --rebase --autostash

      - name: Commit README Update
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Updated Quote"

      - name: Pull Again to Avoid Conflicts
        run: git pull origin main --rebase --autostash

      - name: Push to Main Branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push origin main
          echo "Push to main branch completed."
      - name: Notify Completion
        run: echo "README update completed successfully."
      - name: Notify Failure
        if: failure()
        run: echo "README update failed."
      - name: Notify Success
        if: success()
        run: echo "README update succeeded."
