name: Update README with Random Quote

on:
  schedule:
    - cron: "0 * * * *" # Jalan setiap jam
  workflow_dispatch: # Bisa dijalankan manual dari GitHub Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Full Access)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # Ambil semua history biar bisa push

      - name: Set Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Run Script to Generate Quote
        run: node quote_generator.mjs

      - name: Debug README Content
        run: cat README.md

      - name: Pull Latest Changes (Avoid Push Error)
        run: git pull origin main --rebase

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add README.md
          git commit -m "Updated Quote" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
      - name: Debug Push Result
        run: |
          echo "Push result: $?"
          echo "Git status:"
          git status
          echo "Git log:"
          git log -n 5
          echo "Current branch:"
          git branch --show-current
          echo "Remote URL:"
          git remote -v
          echo "Last commit message:"
          git log -1 --pretty=%B